version: "3.9"
services:
  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "stellar"
      WORDPRESS_DB_NAME: wordpress
    restart: always

  mysql:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "stellar"
    platform: linux/x86_64
    volumes:
      - ./mysql:/var/lib/mysql
